name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and deploy
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
        cd ~
        rm -rf enc
        git config --global user.email "yashoswal18@gmail.com"
        git config --global user.name "mergebot"
        git clone --branch main https://github.com/Itzmeproman/Enc.git
        cd Enc
        git fetch origin
        git checkout main
        git pull origin main
        docker build -t encoder:latest .
        docker stop encoder || true
        docker rm encoder || true
        docker run -d --name encoder -p 2973:2973 encoder:latest
        EOF
